"""Add unique constraint on title+description

Revision ID: 0cce2f7085ef
Revises: 58f22a6a75dd
Create Date: 2025-07-04 02:04:29.280916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cce2f7085ef'
down_revision: Union[str, Sequence[str], None] = '58f22a6a75dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_event_title'), 'events', type_='unique')
    op.create_unique_constraint('uq_event_title_description', 'events', ['title', 'description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_title_description', 'events', type_='unique')
    op.create_unique_constraint(op.f('uq_event_title'), 'events', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
