"""add interests into event model

Revision ID: 49719c7fbc8d
Revises: 83641b7b6abd
Create Date: 2025-06-26 21:17:21.773231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49719c7fbc8d'
down_revision: Union[str, Sequence[str], None] = '83641b7b6abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_interest_association',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_interest_association')
    # ### end Alembic commands ###
