"""Add unique constraint to username

Revision ID: 7ee097a4c912
Revises: 33249b6b8eda
Create Date: 2025-06-24 21:22:26.433061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee097a4c912'
down_revision: Union[str, Sequence[str], None] = '33249b6b8eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('user_event_feedback', 'like',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('user_event_feedback', 'like',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
