"""Add event, interest, date_location models

Revision ID: a13d1d48c066
Revises: d0b6a7925cdc
Create Date: 2025-07-04 01:04:50.736233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13d1d48c066'
down_revision: Union[str, Sequence[str], None] = 'd0b6a7925cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    op.create_unique_constraint('uq_event_title', 'events', ['title'])
    op.add_column('interests', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interests', 'interests', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.drop_column('interests', 'parent_id')
    op.drop_constraint('uq_event_title', 'events', type_='unique')
    op.drop_column('events', 'is_active')
    # ### end Alembic commands ###
